### ISSUE TITLE
Invoice number not shown in synopsis

### ISSUE THREAD

**Issue by lapubell** [open-function-computers-llc/payment-taker#7]
Looks like this didn't make it into the preview:
![image](https://user-images.githubusercontent.com/7433452/101698773-f1871300-3a2e-11eb-9f69-334ec5aa3c51.png)

**Comment by lapubell** [comment]
also not shown on the "receipt" view:
![image](https://user-images.githubusercontent.com/7433452/101699012-517db980-3a2f-11eb-8331-0db0b02d3c18.png)

**Comment by lapubell** [comment]
also looks like that # symbol is what gets passed as meta info to stripe:
![image](https://user-images.githubusercontent.com/7433452/101699221-a4f00780-3a2f-11eb-95b6-889a3ac03f98.png)

**Comment by haleybristol** [comment]
@lapubell  This is up on prod
